name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Generate secret_key
        run: ./node_modules/@fastify/secure-session/genkey.js > secret_key
      - name: Run tests
        run: yarn test
      - name: Clean up
        run: rm secret_key

  build:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Set build_sha file
        run: echo ${{ steps.vars.outputs.sha_short }} > build_sha
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/pietvanzoen/gifme:${{ steps.vars.outputs.sha_short }}
      - name: Tag latest
        run: docker tag ghcr.io/pietvanzoen/gifme:${{ steps.vars.outputs.sha_short }} ghcr.io/pietvanzoen/gifme:latest
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Push the Docker image
        run: |
          docker push ghcr.io/pietvanzoen/gifme:${{ steps.vars.outputs.sha_short }}
          docker push ghcr.io/pietvanzoen/gifme:latest
