name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag docker.pkg.github.com/pietvanzoen/gifme/gifme:latest

  publish:
    - name: Login to GitHub Container Registry
      needs: [build, test]
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Push the Docker image
      run: docker push docker.pkg.github.com/pietvanzoen/gifme/gifme:latest
